### ISSUE TITLE
No items were found for query

### ISSUE THREAD

**Issue by scastria** [msintuneappsdk/intune-app-sdk-xamarin#11] opened 2018-05-31 01:14 UTC
I need some help configuring my Xamarin.Forms iOS app to integrate with Intune SDK.  My app has already been using ADAL v2 to authenticate users.  Here are my issues:

1. The Intune SDK docs for Xamarin.iOS mention ADAL but do not say v1 or v2.  Does it matter?
2. When filling out the keychain access groups, I already had my wildcard with group prefix present as required by ADAL v2.  So all I added was com.microsoft.intune.mam and com.microsoft.adalcache.  However, the screenshot in the instructions also show 2 more keychain groups, one with the app's bundle id and another with the app's bundle id followed by ".intunemam".  Are those needed?
3. When filling out the plist file with the IntuneMAMSettings dictionary, I added my ADALClientId and ADALRedirectUri.  I did NOT know what to put for ADALAuthority so I omitted that one.  Is that required?  If so, what value do I use?
4. In my code after I AquireToken during the user's signin, I then call the Microsoft.Graph API to request ME.  This gives me a User object which contains the UPN.  I then make the call to RegisterAndEnrollAccount with that UPN.  Nothing happens other then the following printed to the console:

    `INFO: No items were found for query: (resource <(null)> + client <(null)> + authority <(null)>)`

Any help would be appreciated.

**Comment by Kyle-Reis** [comment] 2018-05-31 15:39
Hey @scastria. Are you using Windows or Mac for development? If you're using Windows, take a look at issue #6 and the workaround mentioned there. This issue will be addressed in our next release so you won't need to do this moving forward.

1.) We support ADAL v2, however the current version of the native SDK that is included in the bindings only supports up to version 2.5.4. We will support ADAL 2.6+ once we move to version 8+ of the native SDK. 
2.) The app's bundle ID should be the first entry in the list. The bundle ID with the ".intunemam" suffix is not required. Take a look at the entitlements.plist source and ensure that $(AppIdentifierPrefix) is inserted before each entry and that you're not being affected by [this VS issue](https://developercommunity.visualstudio.com/content/problem/258683/ios-appidentifierprefix-is-not-inserted-before-the.html) or something similar to it. If needed, add the prefix to each entry.
3.) You can omit the ADALAuthority and the SDK should get it from the token it finds in the cache.
4.) Let's see what happens once we take care of all the above

**Comment by Kyle-Reis** [comment] 2018-06-05 19:29
Ah, by ADAL v2, I thought you meant that you had created a Xamarin Bindings for version 2.x of  [ADAL for objective-C](https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases). I did not realize the you meant the AAD v2 endpoint. The Microsoft.Identyity.Client NuGet package you are using is a pre-release version of MSAL for .Net, which we do not yet support. Our NuGet package does contain ADAL for objective-C version 2.5.4, and the issue you are seeing is caused by the fact that token sharing between ADAL for Objective-C and .Net is [not yet supported](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1074). I'm following up to see if there is any plan to enable this in the future, as the [roadmap](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki#roadmap) referenced in that issue only mentions token sharing between ADAL and MSAL for .Net. But for now, it looks like your options are as follows:

Option 1: Let the Intune SDK handle authentication by calling IntuneMAMEnrollmentManager.Instance.LoginAndEnrollAccount([NullAllowed] string identity);

Option 2: Create Xamarin bindings for [version 2.5.4 of ADAL for Objective-C](https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases/tag/2.5.4) and use them to acquire an access token and call IntuneMAMEnrollmentManager.Instance.RegisterAndEnrollAccount(string identity);

**Comment by scastria** [comment] 2018-06-06 06:29
I think I have to give up.  This seems to be over my head.  Here is what I attempted:

1. Removed the Identity client nuget package and tried to build
2. Got build errors in my usage of AcquireTokenAsync which was coming from the Identity client nuget package and the v2 endpoint.
3. Got build errors in my AppDelegate where I had to override OpenUrl to handle the authentication continuation used by the v2 endpoint.
4. I assume by using the builtin 2.5.4 ADAL from the Intune nuget, that is a v1 endpoint??  I think v1 endpoint does not have the advantage of allowing all kinds of Microsoft accounts to be authenticated??  I need both personal and work Microsoft accounts to work with my app.
5. If 2.5.4 ADAL is a v1 endpoint, do I have to register my app in a different dashboard?  I think I remember that v1 endpoint has a different app registration dashboard than v2 endpoint.
6. I replaced my AcquireTokenAsync with LoginAndEnrollAccount(null).  I assume I pass in null since I don't know what the identity is as I expect an embedded browser to open and start the authentication process.
7. When I ran this change, an embedded browser DID popup, but to my surprise, the LoginAndEnrollAccount returned immediately.  I was expecting that to block during the embedded browser authentication part just like AcquireTokenAsync does.  So now how do I know when the login and enroll is complete?  Perhaps I add event handlers to EnrollmentRequestWithStatus like the old style callback method instead of the new async/await style.
8. After all of this, I attempted to proceed through the embedded browser authentication process and received an error: 

`2018-06-06 00:01:09.219 Facilities.iOS[19929:6305445] ADAL 2.5.4 iOS 11.3.1 [2018-06-06 06:01:09] ERROR: Error raised: (Domain: "ADOAuthServerErrorDomain" Code: AD_ERROR_SERVER_AUTHORIZATION_CODE ProtocolCode: "access_denied" Details: "AADSTS65005: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: XXXXX. Resource value from request: https://msmamservice.api.application. Resource app ID: 0a5f63c0-b750-4f38-a71c-4fc0d58b89e2. List of valid resources from app registration: 00000003-0000-0000-c000-000000000000.
`

I am not sure what this means, but this morning before this testing, IT informed me that they added my app to their InTune whitelist.

I think I really need some handholding here.  Is there any developer resource that I can get on the phone with to walk me through all of this?  I am happy to pay for it if it is reasonable.

**Comment by Kyle-Reis** [comment] 2018-06-12 14:08
Yes, the built-in version of ADAL talks to the v1 endpoint, and I believe you are correct in that there are separate registration portals for apps which use the v1 and v2 endpoints. The Intune SDK does not yet support the v2 endpoint, as there has not been a release of ADAL for Objective-C which supports the v2 endpoint, and MSAL for Objective-C is still in preview. To be notified of enrollment success/failure, you will need to implement the appropriate methods in a class which inherits from  IntuneMAMEnrollmentDelegate  and set the IntuneMAMEnrollmentManager.Instance.Delegate property to an instance of that class. You can see an example of this in our [Xamarin.iOS sample app](https://github.com/msintuneappsdk/sample-intune-xamarin-ios). The "access_denied" issue you are seeing is occuring because your app's client ID has not yet been given access to the Intune MAM service. I think this should be handled in the partner approval process you mentioned earlier. Since tokens acquired from the v1 and v2 endpoints differ, I don't think there is currently any way to enable SSO between your app and the SDK without changing your app to use the v1 endpoint for enterprise accounts.  I will look into setting you up with a developer resource and loop in the right folks folks for that.

**Comment by msintuneappsdk** [comment] 2018-06-12 15:15
You can get access to the MAM service by using the following steps.
In the Azure portal
1.	Azure Active Directory resource
2.	Select the App registration they have set up for their workfolders application
3.	In settings under API Access select “Required permission”
4.	Click the “+Add” link
5.	Click “Select an API”
6.	In the search box enter “Microsoft Mobile Application Management”
7.	Select “Microsoft Mobile Application Management” in the list of APIs and click select
8.	Select “Read and Write the User’s App Management Data” and click Select.
9.	Click Done

**Comment by scastria** [comment] 2018-06-26 17:40
I am still waiting on the partner approval process.  It has been 3 weeks so far.  I just submitted another request.

I am not sure what the 9 step instructions above are for.  Is this a way to avoid having to wait for the partner approval process?  If so, which Azure portal is this referring to?  The v2 endpoint registration portal, the v1 endpoint registration portal, or something else?

Any luck and setting me up with a developer resource?

**Comment by scastria** [comment] 2018-06-26 21:20
Also, can you clarify the difference in app registration?  With UWP, iOS, and Android, I as the developer go to a common portal and register my app.  Anybody in the world can then download that app once I publish it to the respective app store.  There is nothing specific about the user of the app within the app itself.

with v2 endpoint (which I now know means MSAL and ADAL means v1 endpoint) had a similar portal for app registration.  This allowed me to give myself an app id that any enterprise user of my app could add to their supported list of applications.  Again, nothing specific about the enterprise user is within the app itself.  In other words, the registered MSAL app id in the portal is specific to me the developer and NOT specific to the enterprise user.

with v1 endpoint, it says to register the app in portal.azure.com.  Which account?  If I am supposed to get each enterprise user to register my app in their own portal, won't I have a different app id for each enterprise user.  Wouldn't that require me to make special builds of my app, one for each enterprise user with their respective app id as registered in their own portal?  sureyly, I have to be wrong on this.

**Comment by scastria** [comment] 2018-06-26 23:21
After playing around and testing using the V1 endpoint sample application Azure-Samples/active-directory-dotnet-native-multitarget, I was able to determine that registering this sample app in 1 AAD portal tenant still allowed users from a different AAD tenant to login to the app.  So somehow registering in 1 tenant makes it available to all other tenants??  Is that what availableToOtherTenants = true in the app registration manifest does??

**Comment by Kyle-Reis** [comment] 2018-08-22 19:00
Yes, setting availableToOtherTenants = true should make the app work for users of different tenants (as it seems like you were able to verify). Is there anything else blocking you at this point?

**Comment by Kyle-Reis** [comment] 2018-08-31 13:49
Closing out this issue as it seems there is no longer anything blocking.

**Closed by Kyle-Reis** 2018-08-31 13:49 UTC

**Comment by Kyle-Reis** [comment] 2018-11-13 23:30
Hey @scastria, just wanted to let you know that SSO between MSAL for .Net and the Intune Xamarin.iOS bindings is now supported in the latest releases of each package. See our [updated documentation](https://docs.microsoft.com/intune/app-sdk-xamarin) for more info

**Comment by scastria** [comment] 2018-11-14 00:40
AWESOME!!
