### ISSUE TITLE
Feature request: provide a callback override to get token from ADAL

### ISSUE THREAD

**Issue by alexrainman** [msintuneappsdk/intune-app-sdk-xamarin#13] opened 2018-08-17 15:59 UTC
Currently, the SDK cannot access ADAL token cache. This is not an issue in Android because of this:

```cs
public class MAMServiceAuthenticationCallback : Java.Lang.Object, IMAMServiceAuthenticationCallback
{
    public string AcquireToken(string p0, string p1, string p2)
    {
        var authenticator = SimpleIoc.Default.GetInstance<IAuthenticator>();
        return authenticator.AccessToken;
    }
}
```

Here i am returning the token that i previously acquired with ADAL.

Can we have something similar in iOS?

**Comment by Kyle-Reis** [comment] 2018-08-27 15:21
This is essentially a duplicate of issue #12.

**Closed by Kyle-Reis** 2018-08-27 15:21 UTC
Labels: duplicate
