### ISSUE TITLE
Enrollment Failed: There was an internal error in the Intune MAM SDK. (Xamarin Forms iOS project)

### ISSUE THREAD

**Issue by IliyanPopov** [msintuneappsdk/intune-app-sdk-xamarin#52] opened 2021-12-07 15:45 UTC
**Describe the bug:**
RegisterAndEnrollAccount method fails with internal error.
Enrollment Failed: There was an internal error in the Intune MAM SDK.  Please see the NSError object for more details.
Strangely the Error object itself is null?!?

**To Reproduce**
After successful MSAL authentication call the IntuneMAMEnrollmentManager.Instance.RegisterAndEnrollAccount(identity) as described in the documentation passing the UPN as argument.

**Expected behavior:**
Ideally the Enrollment should succeed, if it doesn't meaningful error should be captured by the SDK.

**Screenshots and logs:**
![IntuneInternalError](https://user-images.githubusercontent.com/13572259/145059443-1b61270e-48d0-4508-9e14-11e2cb32899f.png)

**Smartphone**
 - Device: iPAD mini 5
 - OS: iOS 15.1

**Intune App SDK Xamarin Bindings**
   "Microsoft.Intune.MAM.Xamarin.iOS" v15.1.3
   "Microsoft.Identity.Client" v4.39.0
   "Xamarin.Forms" v5.0.0.2244
   Xcode version: 13.1

**Additional context:**
We have followed the steps described in the official documentation. No matter what we do (or don't) always the internal error flow occurs.

**Comment by darosal** [comment] 2021-12-08 21:45
@IliyanPopov, can you confirm if you have <RestoreProjectStyle>PackageReference</RestoreProjectStyle> set in your csproj file? I have found the cause for a very similar issue and it only affects projects using PackageReferences to consume nuget packages and doesn't affect apps using a packages.config file.

**Comment by IliyanPopov** [comment] 2021-12-09 07:52
@darosal 
Yes I confirm that. If a new Xamarin.Forms project is created it will use PackageReferences by default.
Quote "By default, PackageReference is used for .NET Core projects, .NET Standard projects, and UWP projects targeting Windows 10 Build 15063 (Creators Update) and later, with the exception of C++ UWP projects."
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by darosal** [comment] 2021-12-10 16:25
Hi @IliyanPopov, thanks for confirming that! We have just released a 15.2.0 version of the iOS MAM Xamarin bindings that should address this issue. It should be available on nuget.org now or shortly. Can you try it and confirm if the "There was an internal error in the Intune MAM SDK. Please see the NSError object for more details." error has gone away?

**Comment by IliyanPopov** [comment] 2021-12-13 08:26
@darosal 
I confirm that it works !!!
I have only updated to 15.2.0, no other code changes were made. RegisterAndEnrollAccount works with the current MSAL implementation. PIN set-up screen is shown as expected.
Big thanks to all the people which were involved in this fast fix!
![IntuneWorks](https://user-images.githubusercontent.com/13572259/145777071-fe1a0a80-2c4d-4435-a19d-1087557e67d3.PNG)

**Comment by darosal** [comment] 2021-12-13 15:16
@IliyanPopov Awesome! I'll be closing out this issue but feel free to open another one if another problem comes up!

**Closed by darosal** 2021-12-13 15:16 UTC
Labels: iOS
