### ISSUE TITLE
iOS AppConfigForIdentity don't has the config values

### ISSUE THREAD

**Issue by Totonti** [msintuneappsdk/intune-app-sdk-xamarin#29] opened 2019-05-29 14:02 UTC
Hi,
In my Xamarin Forms iOS app I enrollment the user correctly but when I try to get the app config policy that I define in intune with the function: IntuneMAMAppConfigManager.Instance.AppConfigForIndentity don´t get anything in FullData.

But if I look into IntuneMAMPolicyManager.Instance in DiagnosticInformation I can see the config data. Can I use this to get the values?

Wich is the right method to get those data from the App Configuration Policy?
Do i missing something ?

Thank you

**Comment by Kyle-Reis** [comment] 2019-05-30 13:24
FYI @Totonti, I've moved this issue to the correct repository, in the future please file all issues for our Xamarin bindings here.

Enrollment is still required for managed devices in order to receive app protection policies and MAM app config.

Now that I know we are dealing with MDM app config in this scenario, I think I know what the issue is :) It sounds like you haven't [configured the required IntuneMAMUPN setting](https://docs.microsoft.com/en-us/intune/data-transfer-between-apps-manage-ios#configure-user-upn-setting-for-microsoft-intune-or-third-party-emm) in the MDM app config policy. That setting is what allows the Intune SDK to determine who the device-managed user is, and determine if we should include the MDM app config in the results when querying our APIs. This would explain why you see the app config entries when passing in a null value but not when passing in the enrolled account.

**Comment by Totonti** [comment] 2019-05-30 20:13
Thanks @Kyle-Reis,
So, what I should do is add an IntuneMAMUPM key with the value {{UserPrincipalName}}, along with the rest of the keys, to the app's configuration. and when the user registers with LoginAndEnrollAccount I can use the enrollment account to get the app config values. 
Is that correct?

**Comment by Kyle-Reis** [comment] 2019-05-30 20:14
Yes.

**Comment by Totonti** [comment] 2019-05-30 21:28
Ok, thanks, tomorrow i will try it.

**Comment by Totonti** [comment] 2019-06-03 15:29
Hi @Kyle-Reis,
I've been testing, putting the value in IntuneMAMUPN and I can not get it to work.
The following error occurs:
![Captura de pantalla 2019-06-03 a las 16 40 53](https://user-images.githubusercontent.com/46727161/58813089-5df7a980-8623-11e9-81c0-6e37c2a5999f.png)

Every time, the app asks me to introduce the user to register but it does not seem to get the enrollment.

**Comment by Totonti** [comment] 2019-06-04 16:53
Hi again,
I have continued testing to see if I saw the problem, I verified that with a managed app the LoginAndEnrollment works well and the AppConfigForIndentity function with the registered user correctly retrieves the values of the configuration policy of the app ( without the key IntuneMAMUPN in the policy). Although I see the same error that in the previous comment .
The difference is that the first app is a VPP app that I have published in the apple store.
![image](https://user-images.githubusercontent.com/46727161/58897869-a5506980-86f9-11e9-95fc-d9cb8543294d.png)

 I'm doing the tests for the client, to show how Intune works and when I try to debug the app, I don't see the login window, the "checking yours organization data access" warning comes up for a moment and then nothing else. Could it be that when debugging something is not right?

Thank you so much for your attention

**Comment by Totonti** [comment] 2019-06-06 09:41
Hi @Kyle-Reis,
I have continued to perform tests. What I have found is that for the B2B app purchased in VPP, no app protection policy was assigned, but if I want to create one, it does not appear in the list of apps. If I click on "+ more apps" and put the bundleId of the app and assign a policy and debugging, the app works well: it performs the user registration and collects the configuration data.
Is this the correct way for this type of app?
Thank you

**Comment by Kyle-Reis** [comment] 2019-06-06 12:34
Hey @Totonti, that is the typical approach for custom line-of-business apps. But for public App Store apps that are made available for any customer to use, developers can submit a request to make the app available in the list of targetable apps.

**Comment by Totonti** [comment] 2019-06-06 13:09
Hi @Kyle-Reis ,
then it is correct since my app is a custom app that I have published in the app store but only for certain B2B clients, who are going to buy licenses through VPP and these clients are those who want to deploy the app through Intune, right?

**Comment by msintuneappsdk** [comment] 2019-06-06 16:02
Hi @Totonti how many separate clients using Intune would be using the app that you are building?

**Comment by Totonti** [comment] 2019-06-06 20:21
Hi @Kyle-Reis, i'm not sure, we develop an app to a client who is the one that offers the app to its own partners.
we are testing the entire process to show to our client how it could be done, and in turn, show it to their partners and they will decide how to deploy the app to their users.

**Comment by Totonti** [comment] 2019-06-11 16:28
hi again @Kyle-Reis ,
now we have a problem with the version of the library Microsoft.Intune.MAM.Xamarin.iOS.
if we use the last one : 10.0.7 it works ok but when we publish in App Center the app crash without error.
And when we use the version 8.1.1.2 when doing the loginandenrollment it remains in the first screen (searching organization data access )and don´t show the login page. And we must close the app, and then if restart the app try to get the configuration policy and don´t get nothing. in the debug screen i see this:

![Captura de pantalla 2019-06-11 a las 17 39 36](https://user-images.githubusercontent.com/46727161/59289416-54e78780-8c76-11e9-923a-c9b636ae01d0.png)

Can you help us, please?

**Comment by Kyle-Reis** [comment] 2019-06-11 17:18
Hey @Totonti, the issue you're describing in 8.1.1.2 is a known bug that we fixed in 10.0.7. I'm not sure what might be causing the crash that you see when deploying via AppCenter. Is the app signed properly for distribution? Are you able to connect the debugger or could you share crash logs?

**Comment by Totonti** [comment] 2019-06-12 07:47
Thank you @Kyle-Reis, I'm going to try to publish in App Center again with the 10.0.7 and get the logs.

**Comment by Totonti** [comment] 2019-06-17 06:15
Hi @Kyle-Reis ,
Apple has rejected the app, has sent us the log file. I enclose it to see if you can see something. If we can not publish it with the latest version of the library, we will not be able to implement it in Intune as we wanted.
[attachment-22441737030596131011459262051.console.log](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/files/3295451/attachment-22441737030596131011459262051.console.log)
Thank you

**Comment by Kyle-Reis** [comment] 2019-06-17 13:40
Hey @Totonti, are you able to reproduce the crash locally? Can you attach a debugger? The log file only contains the following statement repeated several times, and it doesn't appear to be related to Intune:

error	15:38:05.552801 -0700	aclara_meters.iOS	API MISUSE: <private> has no restore identifier but the delegate implements the centralManager:willRestoreState: method. Restoring will not be supported

**Comment by Totonti** [comment] 2019-06-17 21:18
Hi @Kyle-Reis , locally the app works ok. I can not reproduce the crash. In App Center and App store the app crash but in TestFlight it works.
I will try to get the log file from the device console when it crash. 
Thank you

**Comment by Totonti** [comment] 2019-06-18 06:48
Hi @Kyle-Reis ,
I attach the log file from device console. I hope you can see something.
the app is com.aclara.mtu.programmer
Thank you
[Log_Xcode_Console-AppCenter_Mam_10.zip](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/files/3300123/Log_Xcode_Console-AppCenter_Mam_10.zip)

**Comment by Totonti** [comment] 2019-06-28 08:17
Hi @Kyle-Reis ,
Have you had an opportunity to see the log that I sent you?
It is important for us since we can not publish the app with the version 10.0.7 of the library and with the previous version the enrollment does not work.
Thank you

**Comment by Kyle-Reis** [comment] 2019-06-28 14:15
Hey @Totonti, I just noticed this comment - "We sign the app in ad-hoc , with a group of devices. is that correct?" Ad Hoc will only allow the app to be run on designated devices. This may explain why you've been unable to reproduce the issue.  You should choose "App Store" when signing the archive.

**Comment by Totonti** [comment] 2019-06-28 15:04
Hi @Kyle-Reis ,
 we publish the app in the app store connect signing it with "App Store" and it was rejected because tha app crashes at launch. But the same app with the version of MAM 8.1.1.2 is accepted, published and works ok. So i think  it is not the signing of the app.  
It is also very strange that the installation from testflight works.
Thank you

**Comment by Kyle-Reis** [comment] 2019-07-02 00:34
Hey @Totonti, could you try our latest release ([11.0.8](https://www.nuget.org/packages/Microsoft.Intune.MAM.Xamarin.iOS/11.0.8))? That version contains an updated version of Objective-C ADAL, which addresses a crash that may occur depending on the state of the ADAL cache on the device. This might explain the inconsistent behavior you’ve seen.

**Comment by Totonti** [comment] 2019-07-03 10:12
Hi @Kyle-Reis, I have tried the new version and the same thing happens. I have published it in AppStore and they have rejected it because it crashes when it is launched.
although I do not understand why if I install it from TestFlight it works.
It also fails if I upload it to the App Center.
thank you

**Comment by Kyle-Reis** [comment] 2019-07-03 12:04
Hey @Totonto, in the AppCenter case, does it crash on the same device used to test the TestFlight scenario?

**Comment by Totonti** [comment] 2019-07-04 12:08
hi @Kyle-Reis, yes, i use the same device in both cases. 
Attach the console when I try to run the app:
![Captura de pantalla 2019-07-04 a las 14 02 06](https://user-images.githubusercontent.com/46727161/60665473-d5a83680-9e64-11e9-977b-1dc562c060b3.png)
 
thank you

**Comment by Kyle-Reis** [comment] 2019-08-15 16:31
Hey @Totonti, are you still seeing the AppCenter crash?

**Comment by Totonti** [comment] 2019-08-16 09:27
Hi, i'm on vacation right now, but the last time i tried to publish the app
in the apple store they didn't approve it. Although in appcenter the app
worked and in testflight too
Thank you

**Comment by Kyle-Reis** [comment] 2019-08-31 10:17
Hey @totonti, do you know why the app store rejected the app?

**Comment by Totonti** [comment] 2019-09-02 10:20
Hi @Kyle-Reis ,
the answer of AppStore team is:
![image](https://user-images.githubusercontent.com/46727161/64107792-9a01ee00-cd7b-11e9-92f0-ce556509bf0f.png)

I think it doesn't make much sense what they say, since for TestFlight they have approved it.
I attach the log files
[attachment-2948070407650225038aclara (4).log](https://github.com/msintuneappsdk/intune-app-sdk-xamarin/files/3565591/attachment-2948070407650225038aclara.4.log)

Thank you

**Comment by Kyle-Reis** [comment] 2020-04-07 17:37
Hey @Totonti, were you able to get any further explanation on this? Is your app still getting rejected?

**Comment by Totonti** [comment] 2020-04-07 19:18
Hi @Kyle-Reis ,
We updated the sdk to version 11.8.13 and finally the apple store approved the application.
thank you very much

**Closed** 2020-04-07 19:18 UTC
